// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file protos/message/v1/messagegateway_service.proto (package messagegateway.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateMessageRequest, CreateMessageResponse, DeleteMessageRequest, DeleteMessageResponse, EditMessageRequest, EditMessageResponse, GetMessagesRequest, GetMessagesResponse } from "./messagegateway_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * this is a complete fcking shitshow someone needs to clean this up
 *
 * @generated from service messagegateway.v1.MessageGatewayService
 */
export const MessageGatewayService = {
  typeName: "messagegateway.v1.MessageGatewayService",
  methods: {
    /**
     * @generated from rpc messagegateway.v1.MessageGatewayService.CreateMessage
     */
    createMessage: {
      name: "CreateMessage",
      I: CreateMessageRequest,
      O: CreateMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc messagegateway.v1.MessageGatewayService.GetMessages
     */
    getMessages: {
      name: "GetMessages",
      I: GetMessagesRequest,
      O: GetMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc messagegateway.v1.MessageGatewayService.EditMessage
     */
    editMessage: {
      name: "EditMessage",
      I: EditMessageRequest,
      O: EditMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc messagegateway.v1.MessageGatewayService.DeleteMessage
     */
    deleteMessage: {
      name: "DeleteMessage",
      I: DeleteMessageRequest,
      O: DeleteMessageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

