// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file protos/chatroom/v1/chatroomgateway_service.proto (package chatroomgateway.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddUserRequest, AddUserResponse, CreateChannelRequest, CreateChannelResponse, CreateRoomRequest, CreateRoomResponse, DeleteChannelRequest, DeleteChannelResponse, DeleteRoomRequest, DeleteRoomResponse, GetChannelRequest, GetChannelResponse, GetRoomRequest, GetRoomResponse, GetRoomsRequest, GetRoomsResponse, InviteUserRequest, InviteUserResponse, RemoveUserRequest, RemoveUserResponse } from "./chatroomgateway_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chatroomgateway.v1.ChatroomGatewayService
 */
export const ChatroomGatewayService = {
  typeName: "chatroomgateway.v1.ChatroomGatewayService",
  methods: {
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.CreateRoom
     */
    createRoom: {
      name: "CreateRoom",
      I: CreateRoomRequest,
      O: CreateRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.DeleteRoom
     */
    deleteRoom: {
      name: "DeleteRoom",
      I: DeleteRoomRequest,
      O: DeleteRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.GetRoom
     */
    getRoom: {
      name: "GetRoom",
      I: GetRoomRequest,
      O: GetRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.GetRooms
     */
    getRooms: {
      name: "GetRooms",
      I: GetRoomsRequest,
      O: GetRoomsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.CreateChannel
     */
    createChannel: {
      name: "CreateChannel",
      I: CreateChannelRequest,
      O: CreateChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.DeleteChannel
     */
    deleteChannel: {
      name: "DeleteChannel",
      I: DeleteChannelRequest,
      O: DeleteChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.GetChannel
     */
    getChannel: {
      name: "GetChannel",
      I: GetChannelRequest,
      O: GetChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.InviteUser
     */
    inviteUser: {
      name: "InviteUser",
      I: InviteUserRequest,
      O: InviteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.RemoveUser
     */
    removeUser: {
      name: "RemoveUser",
      I: RemoveUserRequest,
      O: RemoveUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatroomgateway.v1.ChatroomGatewayService.AddUser
     */
    addUser: {
      name: "AddUser",
      I: AddUserRequest,
      O: AddUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

