/** @format */

// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file protos/authgateway_service.proto (package authgateway.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  AuthenticateRequest,
  AuthenticateResponse,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  LogoutResponse,
  RegisterRequest,
  RegisterResponse,
} from "./authgateway_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service authgateway.v1.AuthGatewayService
 */
export const AuthGatewayService = {
  typeName: "authgateway.v1.AuthGatewayService",
  methods: {
    /**
     * @generated from rpc authgateway.v1.AuthGatewayService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authgateway.v1.AuthGatewayService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authgateway.v1.AuthGatewayService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authgateway.v1.AuthGatewayService.Authenticate
     */
    authenticate: {
      name: "Authenticate",
      I: AuthenticateRequest,
      O: AuthenticateResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
