// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file v1/message_service.proto (package message.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message message.v1.CreateMessageRequest
 */
export class CreateMessageRequest extends Message<CreateMessageRequest> {
  /**
   * @generated from field: string author = 1;
   */
  author = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: string author_uuid = 3;
   */
  authorUuid = "";

  /**
   * @generated from field: string chat_room_uuid = 4;
   */
  chatRoomUuid = "";

  /**
   * @generated from field: string channel_uuid = 5;
   */
  channelUuid = "";

  constructor(data?: PartialMessage<CreateMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.CreateMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "channel_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateMessageRequest | PlainMessage<CreateMessageRequest> | undefined, b: CreateMessageRequest | PlainMessage<CreateMessageRequest> | undefined): boolean {
    return proto3.util.equals(CreateMessageRequest, a, b);
  }
}

/**
 * @generated from message message.v1.CreateMessageResponse
 */
export class CreateMessageResponse extends Message<CreateMessageResponse> {
  /**
   * @generated from field: string author = 1;
   */
  author = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: string author_uuid = 3;
   */
  authorUuid = "";

  /**
   * @generated from field: string chat_room_uuid = 4;
   */
  chatRoomUuid = "";

  /**
   * @generated from field: string channel_uuid = 5;
   */
  channelUuid = "";

  /**
   * @generated from field: string timestamp = 6;
   */
  timestamp = "";

  constructor(data?: PartialMessage<CreateMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.CreateMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "channel_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateMessageResponse | PlainMessage<CreateMessageResponse> | undefined, b: CreateMessageResponse | PlainMessage<CreateMessageResponse> | undefined): boolean {
    return proto3.util.equals(CreateMessageResponse, a, b);
  }
}

/**
 * @generated from message message.v1.GetMessageRequest
 */
export class GetMessageRequest extends Message<GetMessageRequest> {
  /**
   * @generated from field: string chat_room_uuid = 1;
   */
  chatRoomUuid = "";

  constructor(data?: PartialMessage<GetMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.GetMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMessageRequest | PlainMessage<GetMessageRequest> | undefined, b: GetMessageRequest | PlainMessage<GetMessageRequest> | undefined): boolean {
    return proto3.util.equals(GetMessageRequest, a, b);
  }
}

/**
 * @generated from message message.v1.GetMessageResponse
 */
export class GetMessageResponse extends Message<GetMessageResponse> {
  /**
   * @generated from field: string author = 1;
   */
  author = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: string author_uuid = 3;
   */
  authorUuid = "";

  /**
   * @generated from field: string chat_room_uuid = 4;
   */
  chatRoomUuid = "";

  /**
   * @generated from field: string timestamp = 5;
   */
  timestamp = "";

  constructor(data?: PartialMessage<GetMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.GetMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMessageResponse | PlainMessage<GetMessageResponse> | undefined, b: GetMessageResponse | PlainMessage<GetMessageResponse> | undefined): boolean {
    return proto3.util.equals(GetMessageResponse, a, b);
  }
}

/**
 * @generated from message message.v1.EditMessageRequest
 */
export class EditMessageRequest extends Message<EditMessageRequest> {
  /**
   * @generated from field: string author = 1;
   */
  author = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: string author_uuid = 3;
   */
  authorUuid = "";

  /**
   * @generated from field: string chat_room_uuid = 4;
   */
  chatRoomUuid = "";

  /**
   * @generated from field: string timestamp = 5;
   */
  timestamp = "";

  constructor(data?: PartialMessage<EditMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.EditMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EditMessageRequest {
    return new EditMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EditMessageRequest {
    return new EditMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EditMessageRequest {
    return new EditMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EditMessageRequest | PlainMessage<EditMessageRequest> | undefined, b: EditMessageRequest | PlainMessage<EditMessageRequest> | undefined): boolean {
    return proto3.util.equals(EditMessageRequest, a, b);
  }
}

/**
 * @generated from message message.v1.EditMessageResponse
 */
export class EditMessageResponse extends Message<EditMessageResponse> {
  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<EditMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.EditMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EditMessageResponse {
    return new EditMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EditMessageResponse {
    return new EditMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EditMessageResponse {
    return new EditMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EditMessageResponse | PlainMessage<EditMessageResponse> | undefined, b: EditMessageResponse | PlainMessage<EditMessageResponse> | undefined): boolean {
    return proto3.util.equals(EditMessageResponse, a, b);
  }
}

/**
 * @generated from message message.v1.DeleteMessageRequest
 */
export class DeleteMessageRequest extends Message<DeleteMessageRequest> {
  /**
   * @generated from field: string author = 1;
   */
  author = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: string author_uuid = 3;
   */
  authorUuid = "";

  /**
   * @generated from field: string chat_room_uuid = 4;
   */
  chatRoomUuid = "";

  /**
   * @generated from field: string timestamp = 5;
   */
  timestamp = "";

  constructor(data?: PartialMessage<DeleteMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.DeleteMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "chat_room_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteMessageRequest | PlainMessage<DeleteMessageRequest> | undefined, b: DeleteMessageRequest | PlainMessage<DeleteMessageRequest> | undefined): boolean {
    return proto3.util.equals(DeleteMessageRequest, a, b);
  }
}

/**
 * @generated from message message.v1.DeleteMessageResponse
 */
export class DeleteMessageResponse extends Message<DeleteMessageResponse> {
  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<DeleteMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "message.v1.DeleteMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteMessageResponse | PlainMessage<DeleteMessageResponse> | undefined, b: DeleteMessageResponse | PlainMessage<DeleteMessageResponse> | undefined): boolean {
    return proto3.util.equals(DeleteMessageResponse, a, b);
  }
}

