// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file protos/account/v1/accountgateway_service.proto (package accountgateway.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChangePasswordRequest, ChangePasswordResponse, ChangeUsernameRequest, ChangeUsernameResponse, DeleteAccountRequest, DeleteAccountResponse } from "./accountgateway_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service accountgateway.v1.AccountGatewayService
 */
export const AccountGatewayService = {
  typeName: "accountgateway.v1.AccountGatewayService",
  methods: {
    /**
     * External RPC
     *
     * @generated from rpc accountgateway.v1.AccountGatewayService.ChangeUsername
     */
    changeUsername: {
      name: "ChangeUsername",
      I: ChangeUsernameRequest,
      O: ChangeUsernameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc accountgateway.v1.AccountGatewayService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: ChangePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc accountgateway.v1.AccountGatewayService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: DeleteAccountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

